1. Create the Database

In [6]:
students <- data.frame(
  Student_ID= c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
  Programming_Grade= c(88,72,91,78,65,85,74,82),
  Math_Grade= c(85,70,88,80,68,90,73,79),
  Attendance= c(92,80,95,88,70,91,76,85),
  Prerequisite= c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)
students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

2. Explore the data

In [7]:
summary(students)
nrow(students)
ncol(students)

cat("\n")

max(students$Programming_Grade)
max(students$Math_Grade)
max(students$Attendance)
max(students$Prerequisite)

cat("\n")

min(students$Prerequisite)

cat("\n")
sum(students$Programming_Grade)
cat("\n")
mean(students$Math_Grade)
cat("\n")
ave(students$Attendance)

     Student_ID Programming_Grade   Math_Grade      Attendance
 Length   :8    Min.   :65.00     Min.   :68.00   Min.   :70.00
 N.unique :8    1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 N.blank  :0    Median :80.00     Median :79.50   Median :86.50
 Min.nchar:4    Mean   :79.38     Mean   :79.12   Mean   :84.62
 Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
                Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

[1] 8

[1] 5

[1] 91

[1] 90

[1] 95

[1] "Yes"

[1] "No"

[1] 635

[1] 79.125

[1] 84.625 84.625 84.625 84.625 84.625 84.625 84.625 84.625

3. Enter a Student ID

In [8]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S001
[1] "S001"

4. Search the data frame

In [9]:
student <- students[
  students$Student_ID == student_id,
]
student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

CHECK IF THE STUDENT EXIST

In [10]:
if (nrow(student) > 0) {
  print("Found")
} else {
  print("Not Found")
}

[1] "Found"

EXTRACT STUDENT INFORMATION

In [14]:
programming <- student$Programming_Grade
math <- student$Math_Grade
attendance <- student$Attendance
prereq <- student$Prerequisite

cat("Programming Grade:", programming)
cat("\nMath Grade:", math)
cat("\nAttendance:", attendance, "%")
cat("\nPrerequisite:", prereq)

Programming Grade: 88
Math Grade: 85
Attendance: 92 %
Prerequisite: Yes

IMPLEMENT RULES

In [15]:
if (programming >= 80 &&
    math >= 75 &&
    attendance >= 80 &&
    prereq == "Yes") {

  classification <- "Eligible"

} else if (programming >= 75 &&
           math >= 70 &&
           attendance >= 75) {

  classification <- "Conditionally Eligible"

} else {

  classification <- "Not Eligible"
}

cat("\nClassification:", classification)

Classification: Eligible

APPLY THE FUNCTION TO ALL STUDENTS

In [16]:
check_eligibility <- function(programming, math, attendance, prereq) {

  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    return("Eligible")

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    return("Conditionally Eligible")

  } else {

    return("Not Eligible")
  }
}

students$Classification <- mapply(
  check_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Classification
1 Eligible
2 Not Eligible
3 Eligible
4 Conditionally Eligible
5 Not Eligible
6 Eligible
7 Not Eligible
8 Eligible

CREATE RECOMMENDATION RULES

In [17]:
recommendation <- function(programming, math, attendance, prereq) {

  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    return("Highly Recommended")

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    return("Recommended with Improvement")

  } else {

    return("Needs Improvement")
  }
}

students$Recommendation <- mapply(
  recommendation,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Classification         Recommendation
1 Eligible               Highly Recommended
2 Not Eligible           Needs Improvement
3 Eligible               Highly Recommended
4 Conditionally Eligible Recommended with Improvement
5 Not Eligible           Needs Improvement
6 Eligible               Highly Recommended
7 Not Eligible           Needs Improvement
8 Eligible               Highly Recommended

FINAL OUTPUT

In [21]:
# ASK FOR STUDENT ID
student_id <- readline("Enter Student ID: ")

# FIND STUDENT
student <- students[students$Student_ID == student_id, ]

if (nrow(student) == 0) {

  cat("\nStudent not found.\n")

} else {

  # EXTRACT STUDENT INFORMATION
  programming <- student$Programming_Grade
  math <- student$Math_Grade
  attendance <- student$Attendance
  prereq <- student$Prerequisite

  # IMPLEMENT RULES
  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {

    classification <- "Eligible"

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {

    classification <- "Conditionally Eligible"

  } else {

    classification <- "Not Eligible"
  }

  # RECOMMENDATION RULES
  if (classification == "Eligible") {

    recommendation <- "Proceed with enrollment"

  } else if (classification == "Conditionally Eligible") {

    recommendation <- "Consult academic adviser"

  } else {

    recommendation <- "Not recommended for enrollment"
  }

  # FINAL OUTPUT
  cat("\n==========================================\n")
  cat("          COURSE ENROLLMENT ADVISER\n")
  cat("==========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", programming, "\n")
  cat("Math Grade:", math, "\n")
  cat("Attendance:", attendance, "%\n")
  cat("Prerequisite:", prereq, "\n\n")

  cat("Enrollment Status:\n")
  cat(classification, "\n\n")

  cat("Recommendation:\n")
  cat(recommendation, "\n\n")

  cat("==========================================\n")
}

Enter Student ID: S001

==========================================
          COURSE ENROLLMENT ADVISER
==========================================

Student ID: S001

Programming Grade: 88
Math Grade: 85
Attendance: 92 %
Prerequisite: Yes

Enrollment Status:
Eligible

Recommendation:
Proceed with enrollment

==========================================